[package]
name = "logger_proc_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = { version = "2.0.77", features = ["full", "fold"] }
logger = { path = "../logger" }

[lib]
proc-macro = true