[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
smart_stream = { path = "../crates/smart_stream" }
tokio = { version = "1.0", features = ["full"] }
native-tls = "0.2.7"
async-native-tls = "0.3"
