[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
concurrent_runtime = { path = "../crates/concurrent_runtime" }
smtp_server = { path = "../crates/smtp_server" }
ctrlc = "3.4"
